n_channels: 3                 
batch_size: 4              
lr: 0.001                     
margin: 0.0005                
n_epochs: 3                   
scheduler_step: 8             
scheduler_gamma: 0.1          
log_interval: 1            
radius_near: 3000             
radius_far: 5000              
test_size: 0.2                
random_seed: 42               
